name: zenit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.3
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logoipsum-custom-logo.png"
  android_12_splash_screen: true

flutter:
  uses-material-design: true
  
  assets: 
    - assets/images/
  
  fonts:
    - family: MontserratAlternates
      fonts: 
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/MontserratAlternates-Light.ttf
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
